version: 2

sources:
  - name: springml_demo_dataset
    tables:
        - name: sales
          description: 'Sales data'
          columns:
            - name: Transaction_date
            - name: Product
            - name: Price
            - name: Payment_Type
            - name: Name
            - name: City
            - name: State
            - name: Country
            - name: Account_Created
            - name: Last_Login
            - name: Latitude
            - name: Longitude

models:
    - name: payments
      description: "Analysing payment types from sales data"
      columns:
        - name: payment_type
          description: "Payment type: Credit or cash"
          tests:
            - accepted_values:
                values: ['Mastercard', 'Amex', 'Visa', 'Diners']
        - name: number_of_payments
          tests:
            - not_null
        - name: total_price
          tests:
            - not_null
    
    - name: creditcards
      description: "Viewing credit card payment counts by country"
      columns:
        - name: country
          tests:
            - unique
            - not_null
        - name: Amex_payments
          tests:
            - not_null
        - name: Mastercard_payments
          tests:
            - not_null
        - name: Visa_payments
          tests:
            - not_null
    